name: Deploy to GitHub Pages
on: [push]

env:
  GODOT_VERSION: 3.5.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $EXPORT_NAME
          godot -v --export "HTML5"

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: HTML5
          path: Builds/HTML5

      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: Builds/HTML5
